#= require_tree ./mixins
#= require_tree ./initializers
#= require ./store
#= require_tree ./models
#= require_self
#= require_tree ./controllers
#= require_tree ./singletons
#= require_tree ./views
#= require_tree ./components
#= require_tree ./templates
#= require_tree ./routes
#= require ./router
